scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: box_filter
      type: laser_filters/LaserScanBoxFilter
      params:
        box_frame: base_link
        max_x: 0.3
        max_y: 0.23
        max_z: 0.05
        min_x: -0.3
        min_y: -0.23
        min_z: -0.1
